# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://idemo.bspb.ru/auth?response_type=code&client_id=1&redirect_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fsuccess&prefetch_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fprefetch&force_new_session=true&state=%2Fstatement")
    self.driver.set_window_size(1051, 806)
    self.driver.find_element(By.ID, "login-button").click()
    self.driver.find_element(By.ID, "login-otp-button").click()
    self.driver.find_element(By.ID, "deposits-index").click()
    self.driver.find_element(By.ID, "btn-show-rates").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(8) .btn").click()
    self.driver.find_element(By.ID, "amount").click()
    self.driver.find_element(By.ID, "amount").send_keys("100000")
    self.driver.find_element(By.ID, "submit-button").click()
    self.driver.find_element(By.NAME, "condition.newDepositConditions").click()
    self.driver.find_element(By.NAME, "condition.instantDepositAgreement").click()
    element = self.driver.find_element(By.NAME, "condition.instantDepositAgreement")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "accept-instant-deposit-agreement-button").click()
    self.driver.find_element(By.ID, "confirm").click()
    element = self.driver.find_element(By.ID, "confirm")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
